# Generated by Django 5.2.3 on 2025-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dt_nasc', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('senha', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=1)),
            ],
        ),
    ]
