# Generated by Django 5.2.3 on 2025-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='telefone',
        ),
        migrations.AddField(
            model_name='participantes',
            name='aceita_termos',
            field=models.BooleanField(default=False),
        ),
    ]
