# Generated by Django 5.2.3 on 2025-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
