# Generated by Django 5.2.3 on 2025-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0002_alter_participantes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='telefone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
