# Generated by Django 5.2.3 on 2025-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0003_alter_participantes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
