# Generated by Django 5.2.3 on 2025-08-01 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=255)),
                ('cnpj_loja', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=100)),
                ('imagem_cupom', models.ImageField(blank=True, null=True, upload_to='cupons/')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('hora_cadastro', models.TimeField(auto_now_add=True)),
                ('dados_cupom', models.TextField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True, verbose_name='Texto OCR bruto')),
                ('link_consulta', models.URLField(blank=True, null=True)),
                ('dados_json', models.JSONField(default=dict)),
                ('tipo_envio', models.CharField(default='Sistema', max_length=50)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.participantes')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroDaSorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupons.cupom')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.participantes')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_sorte', models.CharField(max_length=60)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='cupons.cupom')),
            ],
        ),
    ]
