# Generated by Django 5.2.3 on 2025-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='dados_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
