# Generated by Django 5.2.3 on 2025-07-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='imagem_cupom',
            field=models.ImageField(blank=True, null=True, upload_to='cupons/'),
        ),
    ]
