# Generated by Django 5.2.3 on 2025-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0002_alter_cupom_dados_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Aberto', max_length=50)),
            ],
        ),
    ]
