# Generated by Django 5.2.3 on 2025-07-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0002_alter_cupom_imagem_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
