# Generated by Django 5.2.3 on 2025-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0003_alter_cupom_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='dados_cupom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
