# Generated by Django 5.2.3 on 2025-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0003_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='nome_serie',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='numero_atual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
