# Generated by Django 5.2.3 on 2025-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0004_cupom_dados_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto OCR bruto'),
        ),
    ]
