# Generated by Django 5.2.3 on 2025-07-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0005_cupom_ocr_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='ocr_text',
        ),
    ]
